/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;


//import java.util.Timer;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author mario
 */
public class proyecto extends javax.swing.JFrame {

    public Parqueo[] sotano1;
    public Parqueo[] sotano2;
    public Parqueo[] sotano3;
    public long tarifa;

    /**
     * Creates new form proyecto
     */
    public proyecto() {
        initComponents();

        // Inicialización de propiedades
        this.sotano1 = new Parqueo[12];
        this.sotano2 = new Parqueo[9];
        this.sotano3 = new Parqueo[11];
        int i;
        for(i=0; i < sotano1.length; i++){
            this.sotano1[i] = new Parqueo(1,i+1);
        }
        for(i=0; i < sotano2.length; i++){
            this.sotano2[i] = new Parqueo(2,i+1);
        }
        for(i=0; i < sotano3.length; i++){
            this.sotano3[i] = new Parqueo(3,i+1);
        }

        this.contarParqueos();
        this.marcarParqueos();

        // Tarifa por fracción definida en el
        this.tarifa = 400; // Centavos (por redondeo)
    }

    private void marcarParqueos() {
        this.Parqueo301.setBackground(this.sotano3[0].libre() == 1?Color.GREEN:Color.RED);
    }

   private void contarParqueos () {
        int libre;
        int libres = 0;

        libre = 0;
        for(int i = 0 ; i < this.sotano1.length; i++) {
            libre+= this.sotano1[i].libre();
        }
        libres+=libre;
        lSotano1Libre.setText(Integer.toString(libre));
        lSotano1ocupado.setText(Integer.toString(this.sotano1.length-libre));

        libre = 0;
        for(int i = 0 ; i < this.sotano2.length; i++) {
            libre+= this.sotano2[i].libre();
        }
        libres+=libre;
        lSotano2libre.setText(Integer.toString(libre));
        lSotano2ocupado.setText(Integer.toString(this.sotano2.length-libre));

        libre = 0;
        for(int i = 0 ; i < this.sotano3.length; i++) {
            libre+= this.sotano3[i].libre();
        }
        libres+=libre;
        lSotano3libre.setText(Integer.toString(libre));
        lSotano3ocupado.setText(Integer.toString(this.sotano3.length-libre));

        lTotalLibre.setText(Integer.toString(libres));
        lTotalOcupado.setText(Integer.toString(this.sotano1.length+this.sotano2.length+this.sotano3.length-libres));
    }

    private Parqueo accionParqueo(Parqueo parqueo){
        if( parqueo.libre() == 1){
            if(JOptionPane.showConfirmDialog (null,"¿Desea asignar este parqueo?",null,JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                parqueo.marcarEntrada();
                //JOptionPane.showMessageDialog(rootPane, "Se ha marcado un ingreso");
            }
        } else {
            if(JOptionPane.showConfirmDialog (null,"¿Desea pagar este parqueo?",null,JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                parqueo.marcarSalida();

                /**
                 * @todo Crear texto para el ticket
                 */
                tTicketText.setText("Total a cancelar: "+Float.toString(parqueo.calcularCobro(this.tarifa)));

                dTicket.setModal(true);
                dTicket.setVisible(true);
                parqueo.limpiar();
            }
        }
        return parqueo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fSotano1 = new javax.swing.JFrame();
        lSotano1titulo = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        fSotano2 = new javax.swing.JFrame();
        lSotano2titulo = new javax.swing.JLabel();
        Parqueo201 = new javax.swing.JButton();
        Parqueo206 = new javax.swing.JButton();
        Parqueo207 = new javax.swing.JButton();
        Parqueo202 = new javax.swing.JButton();
        Parqueo208 = new javax.swing.JButton();
        Parqueo203 = new javax.swing.JButton();
        Parqueo204 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        Parqueo209 = new javax.swing.JButton();
        Parqueo205 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        bSotano2regresar = new javax.swing.JButton();
        fSotano3 = new javax.swing.JFrame();
        lSotano3titulo = new javax.swing.JLabel();
        Parqueo301 = new javax.swing.JButton();
        Parqueo303 = new javax.swing.JButton();
        Parqueo305 = new javax.swing.JButton();
        Parqueo307 = new javax.swing.JButton();
        Parqueo309 = new javax.swing.JButton();
        Parqueo311 = new javax.swing.JButton();
        Parqueo302 = new javax.swing.JButton();
        Parqueo304 = new javax.swing.JButton();
        Parqueo306 = new javax.swing.JButton();
        Parqueo308 = new javax.swing.JButton();
        Parqueo310 = new javax.swing.JButton();
        Parqueo312 = new javax.swing.JButton();
        Parqueo314 = new javax.swing.JButton();
        bSotano3regresar = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        dTicket = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        tTicketText = new javax.swing.JTextArea();
        bCerrarTicket = new javax.swing.JButton();
        bSotano1ir = new javax.swing.JButton();
        bSotano2ir = new javax.swing.JButton();
        bSotano3ir = new javax.swing.JButton();
        lSotano1Libre = new javax.swing.JLabel();
        lSotano1ocupado = new javax.swing.JLabel();
        lSotano2libre = new javax.swing.JLabel();
        lSotano2ocupado = new javax.swing.JLabel();
        lSotano3libre = new javax.swing.JLabel();
        lSotano3ocupado = new javax.swing.JLabel();
        lTotalLibre = new javax.swing.JLabel();
        lTotalOcupado = new javax.swing.JLabel();

        lSotano1titulo.setText("Sotano 1");

        jButton4.setText("jButton4");
        jButton4.setPreferredSize(new java.awt.Dimension(50, 75));

        jButton5.setText("jButton5");
        jButton5.setPreferredSize(new java.awt.Dimension(50, 75));

        jButton6.setText("jButton6");
        jButton6.setPreferredSize(new java.awt.Dimension(50, 75));

        jButton7.setText("jButton7");
        jButton7.setPreferredSize(new java.awt.Dimension(50, 75));

        jButton8.setText("jButton8");
        jButton8.setPreferredSize(new java.awt.Dimension(50, 75));

        jButton9.setText("jButton9");
        jButton9.setPreferredSize(new java.awt.Dimension(50, 75));

        jButton10.setText("jButton10");
        jButton10.setPreferredSize(new java.awt.Dimension(50, 75));

        jButton11.setText("jButton11");
        jButton11.setPreferredSize(new java.awt.Dimension(50, 75));

        jButton12.setText("jButton12");
        jButton12.setPreferredSize(new java.awt.Dimension(50, 75));

        jButton13.setText("jButton13");
        jButton13.setPreferredSize(new java.awt.Dimension(50, 75));

        jButton15.setText("jButton15");
        jButton15.setPreferredSize(new java.awt.Dimension(100, 100));

        jButton16.setText("jButton16");
        jButton16.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout fSotano1Layout = new javax.swing.GroupLayout(fSotano1.getContentPane());
        fSotano1.getContentPane().setLayout(fSotano1Layout);
        fSotano1Layout.setHorizontalGroup(
            fSotano1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fSotano1Layout.createSequentialGroup()
                .addGroup(fSotano1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fSotano1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lSotano1titulo))
                    .addGroup(fSotano1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(fSotano1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(fSotano1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(fSotano1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(fSotano1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(fSotano1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fSotano1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124)))
                .addContainerGap(256, Short.MAX_VALUE))
        );
        fSotano1Layout.setVerticalGroup(
            fSotano1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fSotano1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lSotano1titulo)
                .addGap(61, 61, 61)
                .addGroup(fSotano1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(121, 121, 121)
                .addGroup(fSotano1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(fSotano1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        fSotano2.setSize(new java.awt.Dimension(800, 500));

        lSotano2titulo.setText("Sotano 2");

        Parqueo201.setText("01");

        Parqueo206.setText("06");

        Parqueo207.setText("07");

        Parqueo202.setText("02");

        Parqueo208.setText("08");

        Parqueo203.setText("03");

        Parqueo204.setText("04");

        jButton21.setText("jButton1");

        Parqueo209.setText("09");

        Parqueo205.setText("05");

        jButton24.setText("Regresar");

        bSotano2regresar.setText("Regresar");

        javax.swing.GroupLayout fSotano2Layout = new javax.swing.GroupLayout(fSotano2.getContentPane());
        fSotano2.getContentPane().setLayout(fSotano2Layout);
        fSotano2Layout.setHorizontalGroup(
            fSotano2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fSotano2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lSotano2titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(fSotano2Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(fSotano2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bSotano2regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fSotano2Layout.createSequentialGroup()
                        .addGroup(fSotano2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Parqueo206, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Parqueo201, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(fSotano2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Parqueo207, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Parqueo202, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(fSotano2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Parqueo208, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Parqueo203, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43)
                .addGroup(fSotano2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fSotano2Layout.createSequentialGroup()
                        .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(fSotano2Layout.createSequentialGroup()
                        .addGroup(fSotano2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Parqueo209, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(fSotano2Layout.createSequentialGroup()
                                .addGroup(fSotano2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Parqueo204, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addComponent(Parqueo205, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(13, Short.MAX_VALUE))))
        );
        fSotano2Layout.setVerticalGroup(
            fSotano2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fSotano2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lSotano2titulo)
                .addGap(31, 31, 31)
                .addGroup(fSotano2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fSotano2Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(Parqueo206, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fSotano2Layout.createSequentialGroup()
                        .addGroup(fSotano2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Parqueo202, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Parqueo201, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(fSotano2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Parqueo207, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Parqueo208, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Parqueo209, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Parqueo204, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fSotano2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Parqueo203, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Parqueo205, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(fSotano2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSotano2regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71))
        );

        fSotano3.setSize(new java.awt.Dimension(800, 500));

        lSotano3titulo.setText("Sotano 3");

        Parqueo301.setText("01");
        Parqueo301.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Parqueo301MouseClicked(evt);
            }
        });

        Parqueo303.setText("Parqueo302");
        Parqueo303.setToolTipText("");

        Parqueo305.setText("jButton14");

        Parqueo307.setText("jButton17");

        Parqueo309.setText("jButton18");

        Parqueo311.setText("jButton19");

        Parqueo302.setText("jButton14");

        Parqueo304.setText("jButton17");

        Parqueo306.setText("jButton18");

        Parqueo308.setText("jButton19");

        Parqueo310.setText("jButton20");

        Parqueo312.setText("jButton21");

        Parqueo314.setText("jButton22");

        bSotano3regresar.setText("Regresar");
        bSotano3regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSotano3regresarMouseClicked(evt);
            }
        });

        jButton17.setText("jButton17");

        javax.swing.GroupLayout fSotano3Layout = new javax.swing.GroupLayout(fSotano3.getContentPane());
        fSotano3.getContentPane().setLayout(fSotano3Layout);
        fSotano3Layout.setHorizontalGroup(
            fSotano3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fSotano3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lSotano3titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fSotano3Layout.createSequentialGroup()
                .addGroup(fSotano3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(fSotano3Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(Parqueo301, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(Parqueo303, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(Parqueo305, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(Parqueo307, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Parqueo309, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(Parqueo311, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fSotano3Layout.createSequentialGroup()
                        .addGroup(fSotano3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, fSotano3Layout.createSequentialGroup()
                                .addGap(216, 216, 216)
                                .addComponent(bSotano3regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(146, 146, 146)
                                .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                            .addGroup(fSotano3Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Parqueo302, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(Parqueo304, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(Parqueo306, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(Parqueo308, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(Parqueo310, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39)
                        .addComponent(Parqueo312, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(Parqueo314, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        fSotano3Layout.setVerticalGroup(
            fSotano3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fSotano3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lSotano3titulo)
                .addGroup(fSotano3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fSotano3Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(fSotano3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Parqueo303, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Parqueo305, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Parqueo307, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Parqueo309, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Parqueo311, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Parqueo301, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)
                        .addGroup(fSotano3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Parqueo314, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Parqueo310, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Parqueo312, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Parqueo308, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Parqueo306, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Parqueo304, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Parqueo302, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 104, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fSotano3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(fSotano3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bSotano3regresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        dTicket.setMinimumSize(new java.awt.Dimension(400, 300));
        dTicket.setResizable(false);
        dTicket.setSize(new java.awt.Dimension(400, 300));

        tTicketText.setColumns(20);
        tTicketText.setRows(5);
        jScrollPane2.setViewportView(tTicketText);

        bCerrarTicket.setText("Cerrar");
        bCerrarTicket.setMaximumSize(new java.awt.Dimension(100, 25));
        bCerrarTicket.setMinimumSize(new java.awt.Dimension(100, 25));
        bCerrarTicket.setPreferredSize(new java.awt.Dimension(100, 25));
        bCerrarTicket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCerrarTicketMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout dTicketLayout = new javax.swing.GroupLayout(dTicket.getContentPane());
        dTicket.getContentPane().setLayout(dTicketLayout);
        dTicketLayout.setHorizontalGroup(
            dTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dTicketLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(dTicketLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(bCerrarTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );
        dTicketLayout.setVerticalGroup(
            dTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dTicketLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bCerrarTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bSotano1ir.setToolTipText("");
        bSotano1ir.setLabel("Sotano 1");
        bSotano1ir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSotano1irMouseClicked(evt);
            }
        });

        bSotano2ir.setLabel("Sotano 2");
        bSotano2ir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSotano2irMouseClicked(evt);
            }
        });

        bSotano3ir.setLabel("Sotano 3");
        bSotano3ir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSotano3irMouseClicked(evt);
            }
        });

        lSotano1Libre.setBackground(new java.awt.Color(0, 255, 0));
        lSotano1Libre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lSotano1Libre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lSotano1Libre.setText("0");
        lSotano1Libre.setToolTipText("");
        lSotano1Libre.setMaximumSize(new java.awt.Dimension(25, 17));
        lSotano1Libre.setMinimumSize(new java.awt.Dimension(25, 17));
        lSotano1Libre.setName(""); // NOI18N
        lSotano1Libre.setOpaque(true);
        lSotano1Libre.setPreferredSize(new java.awt.Dimension(25, 17));

        lSotano1ocupado.setBackground(new java.awt.Color(255, 0, 0));
        lSotano1ocupado.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lSotano1ocupado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lSotano1ocupado.setText("0");
        lSotano1ocupado.setToolTipText("");
        lSotano1ocupado.setMaximumSize(new java.awt.Dimension(25, 17));
        lSotano1ocupado.setMinimumSize(new java.awt.Dimension(25, 17));
        lSotano1ocupado.setName(""); // NOI18N
        lSotano1ocupado.setOpaque(true);
        lSotano1ocupado.setPreferredSize(new java.awt.Dimension(25, 17));

        lSotano2libre.setBackground(new java.awt.Color(0, 255, 0));
        lSotano2libre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lSotano2libre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lSotano2libre.setText("0");
        lSotano2libre.setToolTipText("");
        lSotano2libre.setMaximumSize(new java.awt.Dimension(25, 17));
        lSotano2libre.setMinimumSize(new java.awt.Dimension(25, 17));
        lSotano2libre.setName(""); // NOI18N
        lSotano2libre.setOpaque(true);
        lSotano2libre.setPreferredSize(new java.awt.Dimension(25, 17));

        lSotano2ocupado.setBackground(new java.awt.Color(255, 0, 0));
        lSotano2ocupado.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lSotano2ocupado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lSotano2ocupado.setText("0");
        lSotano2ocupado.setToolTipText("");
        lSotano2ocupado.setMaximumSize(new java.awt.Dimension(25, 17));
        lSotano2ocupado.setMinimumSize(new java.awt.Dimension(25, 17));
        lSotano2ocupado.setName(""); // NOI18N
        lSotano2ocupado.setOpaque(true);
        lSotano2ocupado.setPreferredSize(new java.awt.Dimension(25, 17));

        lSotano3libre.setBackground(new java.awt.Color(0, 255, 0));
        lSotano3libre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lSotano3libre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lSotano3libre.setText("0");
        lSotano3libre.setToolTipText("");
        lSotano3libre.setMaximumSize(new java.awt.Dimension(25, 17));
        lSotano3libre.setMinimumSize(new java.awt.Dimension(25, 17));
        lSotano3libre.setName(""); // NOI18N
        lSotano3libre.setOpaque(true);
        lSotano3libre.setPreferredSize(new java.awt.Dimension(25, 17));

        lSotano3ocupado.setBackground(new java.awt.Color(255, 0, 0));
        lSotano3ocupado.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lSotano3ocupado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lSotano3ocupado.setText("0");
        lSotano3ocupado.setToolTipText("");
        lSotano3ocupado.setMaximumSize(new java.awt.Dimension(25, 17));
        lSotano3ocupado.setMinimumSize(new java.awt.Dimension(25, 17));
        lSotano3ocupado.setName(""); // NOI18N
        lSotano3ocupado.setOpaque(true);
        lSotano3ocupado.setPreferredSize(new java.awt.Dimension(25, 17));

        lTotalLibre.setBackground(new java.awt.Color(0, 255, 0));
        lTotalLibre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lTotalLibre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lTotalLibre.setText("0");
        lTotalLibre.setToolTipText("");
        lTotalLibre.setMaximumSize(new java.awt.Dimension(25, 17));
        lTotalLibre.setMinimumSize(new java.awt.Dimension(25, 17));
        lTotalLibre.setName(""); // NOI18N
        lTotalLibre.setOpaque(true);
        lTotalLibre.setPreferredSize(new java.awt.Dimension(25, 17));

        lTotalOcupado.setBackground(new java.awt.Color(255, 0, 0));
        lTotalOcupado.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lTotalOcupado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lTotalOcupado.setText("0");
        lTotalOcupado.setToolTipText("");
        lTotalOcupado.setMaximumSize(new java.awt.Dimension(25, 17));
        lTotalOcupado.setMinimumSize(new java.awt.Dimension(25, 17));
        lTotalOcupado.setName(""); // NOI18N
        lTotalOcupado.setOpaque(true);
        lTotalOcupado.setPreferredSize(new java.awt.Dimension(25, 17));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bSotano1ir)
                    .addComponent(bSotano2ir)
                    .addComponent(bSotano3ir))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lTotalLibre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lTotalOcupado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lSotano3libre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lSotano3ocupado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lSotano2libre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lSotano2ocupado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lSotano1Libre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lSotano1ocupado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSotano1ir)
                    .addComponent(lSotano1Libre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lSotano1ocupado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSotano2ir)
                    .addComponent(lSotano2libre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lSotano2ocupado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSotano3ir)
                    .addComponent(lSotano3libre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lSotano3ocupado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTotalLibre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lTotalOcupado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Parqueo301MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Parqueo301MouseClicked
        this.sotano3[0] = this.accionParqueo(this.sotano3[0]);
        this.marcarParqueos();
    }//GEN-LAST:event_Parqueo301MouseClicked

    private void bSotano1irMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSotano1irMouseClicked
        this.setVisible(false);
        fSotano1.setVisible(true);
    }//GEN-LAST:event_bSotano1irMouseClicked

    private void bSotano2irMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSotano2irMouseClicked
        this.setVisible(false);
        fSotano2.setVisible(true);
    }//GEN-LAST:event_bSotano2irMouseClicked

    private void bSotano3irMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSotano3irMouseClicked
        this.setVisible(false);
        fSotano3.setVisible(true);
    }//GEN-LAST:event_bSotano3irMouseClicked

    private void bSotano3regresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSotano3regresarMouseClicked
        fSotano3.setVisible(false);
        this.setVisible(true);
        this.contarParqueos();
    }//GEN-LAST:event_bSotano3regresarMouseClicked

    private void bCerrarTicketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCerrarTicketMouseClicked
        dTicket.setModal(false);
        dTicket.setVisible(false);
    }//GEN-LAST:event_bCerrarTicketMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new proyecto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Parqueo201;
    private javax.swing.JButton Parqueo202;
    private javax.swing.JButton Parqueo203;
    private javax.swing.JButton Parqueo204;
    private javax.swing.JButton Parqueo205;
    private javax.swing.JButton Parqueo206;
    private javax.swing.JButton Parqueo207;
    private javax.swing.JButton Parqueo208;
    private javax.swing.JButton Parqueo209;
    private javax.swing.JButton Parqueo301;
    private javax.swing.JButton Parqueo302;
    private javax.swing.JButton Parqueo303;
    private javax.swing.JButton Parqueo304;
    private javax.swing.JButton Parqueo305;
    private javax.swing.JButton Parqueo306;
    private javax.swing.JButton Parqueo307;
    private javax.swing.JButton Parqueo308;
    private javax.swing.JButton Parqueo309;
    private javax.swing.JButton Parqueo310;
    private javax.swing.JButton Parqueo311;
    private javax.swing.JButton Parqueo312;
    private javax.swing.JButton Parqueo314;
    private javax.swing.JButton bCerrarTicket;
    private javax.swing.JButton bSotano1ir;
    private javax.swing.JButton bSotano2ir;
    private javax.swing.JButton bSotano2regresar;
    private javax.swing.JButton bSotano3ir;
    private javax.swing.JButton bSotano3regresar;
    private javax.swing.JDialog dTicket;
    private javax.swing.JFrame fSotano1;
    private javax.swing.JFrame fSotano2;
    private javax.swing.JFrame fSotano3;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lSotano1Libre;
    private javax.swing.JLabel lSotano1ocupado;
    private javax.swing.JLabel lSotano1titulo;
    private javax.swing.JLabel lSotano2libre;
    private javax.swing.JLabel lSotano2ocupado;
    private javax.swing.JLabel lSotano2titulo;
    private javax.swing.JLabel lSotano3libre;
    private javax.swing.JLabel lSotano3ocupado;
    private javax.swing.JLabel lSotano3titulo;
    private javax.swing.JLabel lTotalLibre;
    private javax.swing.JLabel lTotalOcupado;
    private javax.swing.JTextArea tTicketText;
    // End of variables declaration//GEN-END:variables
}
